
# Variables:
# iterations:             How many times we will 'wait 10s and retry'
# servergroupname         Name of Server Group to iterate Rules (leave blank for all)
# clientid:               API key
# clientsecret:           API secret
# host:                   API host

iterations: 10
servergroupname: ''
clientid: '1c859dfc'
clientsecret: '57c1f9bcf2447129b11d8dfb812f5a7f'

host: 'api-govcloud.cloudpassage.com'
